# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import artikcloud
from artikcloud.rest import ApiException
from artikcloud.models.contact_info import ContactInfo


class TestContactInfo(unittest.TestCase):
    """ ContactInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactInfo(self):
        """
        Test ContactInfo
        """
        model = artikcloud.models.contact_info.ContactInfo()


if __name__ == '__main__':
    unittest.main()
