# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import artikcloud
from artikcloud.rest import ApiException
from artikcloud.models.device_reg_confirm_user_request import DeviceRegConfirmUserRequest


class TestDeviceRegConfirmUserRequest(unittest.TestCase):
    """ DeviceRegConfirmUserRequest unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceRegConfirmUserRequest(self):
        """
        Test DeviceRegConfirmUserRequest
        """
        model = artikcloud.models.device_reg_confirm_user_request.DeviceRegConfirmUserRequest()


if __name__ == '__main__':
    unittest.main()
