# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ActionOut(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, data=None, cid=None, ddid=None, sdid=None, ts=None, type='action', mid=None, uid=None, sdtid=None, cts=None, mv=None):
        """
        ActionOut - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'data': 'ActionDetailsArray',
            'cid': 'str',
            'ddid': 'str',
            'sdid': 'str',
            'ts': 'int',
            'type': 'str',
            'mid': 'str',
            'uid': 'str',
            'sdtid': 'str',
            'cts': 'int',
            'mv': 'int'
        }

        self.attribute_map = {
            'data': 'data',
            'cid': 'cid',
            'ddid': 'ddid',
            'sdid': 'sdid',
            'ts': 'ts',
            'type': 'type',
            'mid': 'mid',
            'uid': 'uid',
            'sdtid': 'sdtid',
            'cts': 'cts',
            'mv': 'mv'
        }

        self._data = data
        self._cid = cid
        self._ddid = ddid
        self._sdid = sdid
        self._ts = ts
        self._type = type
        self._mid = mid
        self._uid = uid
        self._sdtid = sdtid
        self._cts = cts
        self._mv = mv

    @property
    def data(self):
        """
        Gets the data of this ActionOut.

        :return: The data of this ActionOut.
        :rtype: ActionDetailsArray
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this ActionOut.

        :param data: The data of this ActionOut.
        :type: ActionDetailsArray
        """

        self._data = data

    @property
    def cid(self):
        """
        Gets the cid of this ActionOut.
        Confirmation ID.

        :return: The cid of this ActionOut.
        :rtype: str
        """
        return self._cid

    @cid.setter
    def cid(self, cid):
        """
        Sets the cid of this ActionOut.
        Confirmation ID.

        :param cid: The cid of this ActionOut.
        :type: str
        """

        self._cid = cid

    @property
    def ddid(self):
        """
        Gets the ddid of this ActionOut.
        Destination Device ID.

        :return: The ddid of this ActionOut.
        :rtype: str
        """
        return self._ddid

    @ddid.setter
    def ddid(self, ddid):
        """
        Sets the ddid of this ActionOut.
        Destination Device ID.

        :param ddid: The ddid of this ActionOut.
        :type: str
        """

        self._ddid = ddid

    @property
    def sdid(self):
        """
        Gets the sdid of this ActionOut.
        Source Device ID.

        :return: The sdid of this ActionOut.
        :rtype: str
        """
        return self._sdid

    @sdid.setter
    def sdid(self, sdid):
        """
        Sets the sdid of this ActionOut.
        Source Device ID.

        :param sdid: The sdid of this ActionOut.
        :type: str
        """

        self._sdid = sdid

    @property
    def ts(self):
        """
        Gets the ts of this ActionOut.
        Timestamp (past, present or future). Defaults to current time if not provided.

        :return: The ts of this ActionOut.
        :rtype: int
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """
        Sets the ts of this ActionOut.
        Timestamp (past, present or future). Defaults to current time if not provided.

        :param ts: The ts of this ActionOut.
        :type: int
        """

        self._ts = ts

    @property
    def type(self):
        """
        Gets the type of this ActionOut.
        Type.

        :return: The type of this ActionOut.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ActionOut.
        Type.

        :param type: The type of this ActionOut.
        :type: str
        """

        self._type = type

    @property
    def mid(self):
        """
        Gets the mid of this ActionOut.
        Message ID.

        :return: The mid of this ActionOut.
        :rtype: str
        """
        return self._mid

    @mid.setter
    def mid(self, mid):
        """
        Sets the mid of this ActionOut.
        Message ID.

        :param mid: The mid of this ActionOut.
        :type: str
        """

        self._mid = mid

    @property
    def uid(self):
        """
        Gets the uid of this ActionOut.
        User ID.

        :return: The uid of this ActionOut.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this ActionOut.
        User ID.

        :param uid: The uid of this ActionOut.
        :type: str
        """

        self._uid = uid

    @property
    def sdtid(self):
        """
        Gets the sdtid of this ActionOut.
        Source Device Type ID.

        :return: The sdtid of this ActionOut.
        :rtype: str
        """
        return self._sdtid

    @sdtid.setter
    def sdtid(self, sdtid):
        """
        Sets the sdtid of this ActionOut.
        Source Device Type ID.

        :param sdtid: The sdtid of this ActionOut.
        :type: str
        """

        self._sdtid = sdtid

    @property
    def cts(self):
        """
        Gets the cts of this ActionOut.
        Created Timestamp (past, present or future). Defaults to current time if not provided.

        :return: The cts of this ActionOut.
        :rtype: int
        """
        return self._cts

    @cts.setter
    def cts(self, cts):
        """
        Sets the cts of this ActionOut.
        Created Timestamp (past, present or future). Defaults to current time if not provided.

        :param cts: The cts of this ActionOut.
        :type: int
        """

        self._cts = cts

    @property
    def mv(self):
        """
        Gets the mv of this ActionOut.
        Manifest Version.

        :return: The mv of this ActionOut.
        :rtype: int
        """
        return self._mv

    @mv.setter
    def mv(self, mv):
        """
        Sets the mv of this ActionOut.
        Manifest Version.

        :param mv: The mv of this ActionOut.
        :type: int
        """

        self._mv = mv

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ActionOut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
