# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AppProperties(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uid=None, aid=None, properties=None):
        """
        AppProperties - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'uid': 'str',
            'aid': 'str',
            'properties': 'str'
        }

        self.attribute_map = {
            'uid': 'uid',
            'aid': 'aid',
            'properties': 'properties'
        }

        self._uid = uid
        self._aid = aid
        self._properties = properties

    @property
    def uid(self):
        """
        Gets the uid of this AppProperties.

        :return: The uid of this AppProperties.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this AppProperties.

        :param uid: The uid of this AppProperties.
        :type: str
        """

        self._uid = uid

    @property
    def aid(self):
        """
        Gets the aid of this AppProperties.

        :return: The aid of this AppProperties.
        :rtype: str
        """
        return self._aid

    @aid.setter
    def aid(self, aid):
        """
        Sets the aid of this AppProperties.

        :param aid: The aid of this AppProperties.
        :type: str
        """

        self._aid = aid

    @property
    def properties(self):
        """
        Gets the properties of this AppProperties.

        :return: The properties of this AppProperties.
        :rtype: str
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """
        Sets the properties of this AppProperties.

        :param properties: The properties of this AppProperties.
        :type: str
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")

        self._properties = properties

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AppProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
