# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Device(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, uid=None, dtid=None, name=None, manifest_version=None, manifest_version_policy=None, need_provider_auth=None, properties=None, created_on=None, connected=None, certificate_info=None, certificate_signature=None, eid=None, provider_credentials=None, shared_with_others=None, shared_with_me=None):
        """
        Device - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'uid': 'str',
            'dtid': 'str',
            'name': 'str',
            'manifest_version': 'int',
            'manifest_version_policy': 'str',
            'need_provider_auth': 'bool',
            'properties': 'dict(str, object)',
            'created_on': 'int',
            'connected': 'bool',
            'certificate_info': 'str',
            'certificate_signature': 'str',
            'eid': 'str',
            'provider_credentials': 'dict(str, object)',
            'shared_with_others': 'bool',
            'shared_with_me': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'uid': 'uid',
            'dtid': 'dtid',
            'name': 'name',
            'manifest_version': 'manifestVersion',
            'manifest_version_policy': 'manifestVersionPolicy',
            'need_provider_auth': 'needProviderAuth',
            'properties': 'properties',
            'created_on': 'createdOn',
            'connected': 'connected',
            'certificate_info': 'certificateInfo',
            'certificate_signature': 'certificateSignature',
            'eid': 'eid',
            'provider_credentials': 'providerCredentials',
            'shared_with_others': 'sharedWithOthers',
            'shared_with_me': 'sharedWithMe'
        }

        self._id = id
        self._uid = uid
        self._dtid = dtid
        self._name = name
        self._manifest_version = manifest_version
        self._manifest_version_policy = manifest_version_policy
        self._need_provider_auth = need_provider_auth
        self._properties = properties
        self._created_on = created_on
        self._connected = connected
        self._certificate_info = certificate_info
        self._certificate_signature = certificate_signature
        self._eid = eid
        self._provider_credentials = provider_credentials
        self._shared_with_others = shared_with_others
        self._shared_with_me = shared_with_me

    @property
    def id(self):
        """
        Gets the id of this Device.
        Device ID

        :return: The id of this Device.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Device.
        Device ID

        :param id: The id of this Device.
        :type: str
        """

        self._id = id

    @property
    def uid(self):
        """
        Gets the uid of this Device.
        User ID

        :return: The uid of this Device.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this Device.
        User ID

        :param uid: The uid of this Device.
        :type: str
        """

        self._uid = uid

    @property
    def dtid(self):
        """
        Gets the dtid of this Device.
        Device Type ID

        :return: The dtid of this Device.
        :rtype: str
        """
        return self._dtid

    @dtid.setter
    def dtid(self, dtid):
        """
        Sets the dtid of this Device.
        Device Type ID

        :param dtid: The dtid of this Device.
        :type: str
        """

        self._dtid = dtid

    @property
    def name(self):
        """
        Gets the name of this Device.
        Name

        :return: The name of this Device.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Device.
        Name

        :param name: The name of this Device.
        :type: str
        """

        self._name = name

    @property
    def manifest_version(self):
        """
        Gets the manifest_version of this Device.
        Manifest Version

        :return: The manifest_version of this Device.
        :rtype: int
        """
        return self._manifest_version

    @manifest_version.setter
    def manifest_version(self, manifest_version):
        """
        Sets the manifest_version of this Device.
        Manifest Version

        :param manifest_version: The manifest_version of this Device.
        :type: int
        """

        self._manifest_version = manifest_version

    @property
    def manifest_version_policy(self):
        """
        Gets the manifest_version_policy of this Device.
        Manifest Version Policy (LATEST, DEVICE)

        :return: The manifest_version_policy of this Device.
        :rtype: str
        """
        return self._manifest_version_policy

    @manifest_version_policy.setter
    def manifest_version_policy(self, manifest_version_policy):
        """
        Sets the manifest_version_policy of this Device.
        Manifest Version Policy (LATEST, DEVICE)

        :param manifest_version_policy: The manifest_version_policy of this Device.
        :type: str
        """

        self._manifest_version_policy = manifest_version_policy

    @property
    def need_provider_auth(self):
        """
        Gets the need_provider_auth of this Device.
        Needs Provider Authentication

        :return: The need_provider_auth of this Device.
        :rtype: bool
        """
        return self._need_provider_auth

    @need_provider_auth.setter
    def need_provider_auth(self, need_provider_auth):
        """
        Sets the need_provider_auth of this Device.
        Needs Provider Authentication

        :param need_provider_auth: The need_provider_auth of this Device.
        :type: bool
        """

        self._need_provider_auth = need_provider_auth

    @property
    def properties(self):
        """
        Gets the properties of this Device.

        :return: The properties of this Device.
        :rtype: dict(str, object)
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """
        Sets the properties of this Device.

        :param properties: The properties of this Device.
        :type: dict(str, object)
        """

        self._properties = properties

    @property
    def created_on(self):
        """
        Gets the created_on of this Device.
        Created On (milliseconds since epoch)

        :return: The created_on of this Device.
        :rtype: int
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """
        Sets the created_on of this Device.
        Created On (milliseconds since epoch)

        :param created_on: The created_on of this Device.
        :type: int
        """

        self._created_on = created_on

    @property
    def connected(self):
        """
        Gets the connected of this Device.
        Is Connected

        :return: The connected of this Device.
        :rtype: bool
        """
        return self._connected

    @connected.setter
    def connected(self, connected):
        """
        Sets the connected of this Device.
        Is Connected

        :param connected: The connected of this Device.
        :type: bool
        """

        self._connected = connected

    @property
    def certificate_info(self):
        """
        Gets the certificate_info of this Device.
        Certificate Info (if any)

        :return: The certificate_info of this Device.
        :rtype: str
        """
        return self._certificate_info

    @certificate_info.setter
    def certificate_info(self, certificate_info):
        """
        Sets the certificate_info of this Device.
        Certificate Info (if any)

        :param certificate_info: The certificate_info of this Device.
        :type: str
        """

        self._certificate_info = certificate_info

    @property
    def certificate_signature(self):
        """
        Gets the certificate_signature of this Device.
        Certificate Signature (if any)

        :return: The certificate_signature of this Device.
        :rtype: str
        """
        return self._certificate_signature

    @certificate_signature.setter
    def certificate_signature(self, certificate_signature):
        """
        Sets the certificate_signature of this Device.
        Certificate Signature (if any)

        :param certificate_signature: The certificate_signature of this Device.
        :type: str
        """

        self._certificate_signature = certificate_signature

    @property
    def eid(self):
        """
        Gets the eid of this Device.
        External ID (if any)

        :return: The eid of this Device.
        :rtype: str
        """
        return self._eid

    @eid.setter
    def eid(self, eid):
        """
        Sets the eid of this Device.
        External ID (if any)

        :param eid: The eid of this Device.
        :type: str
        """

        self._eid = eid

    @property
    def provider_credentials(self):
        """
        Gets the provider_credentials of this Device.

        :return: The provider_credentials of this Device.
        :rtype: dict(str, object)
        """
        return self._provider_credentials

    @provider_credentials.setter
    def provider_credentials(self, provider_credentials):
        """
        Sets the provider_credentials of this Device.

        :param provider_credentials: The provider_credentials of this Device.
        :type: dict(str, object)
        """

        self._provider_credentials = provider_credentials

    @property
    def shared_with_others(self):
        """
        Gets the shared_with_others of this Device.
        Is shared with other users

        :return: The shared_with_others of this Device.
        :rtype: bool
        """
        return self._shared_with_others

    @shared_with_others.setter
    def shared_with_others(self, shared_with_others):
        """
        Sets the shared_with_others of this Device.
        Is shared with other users

        :param shared_with_others: The shared_with_others of this Device.
        :type: bool
        """

        self._shared_with_others = shared_with_others

    @property
    def shared_with_me(self):
        """
        Gets the shared_with_me of this Device.
        Share id (if shared with me)

        :return: The shared_with_me of this Device.
        :rtype: str
        """
        return self._shared_with_me

    @shared_with_me.setter
    def shared_with_me(self, shared_with_me):
        """
        Sets the shared_with_me of this Device.
        Share id (if shared with me)

        :param shared_with_me: The shared_with_me of this Device.
        :type: str
        """

        self._shared_with_me = shared_with_me

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Device):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
