# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DevicesEnvelope(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, total=None, count=None, offset=None, data=None):
        """
        DevicesEnvelope - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'total': 'int',
            'count': 'int',
            'offset': 'int',
            'data': 'DeviceArray'
        }

        self.attribute_map = {
            'total': 'total',
            'count': 'count',
            'offset': 'offset',
            'data': 'data'
        }

        self._total = total
        self._count = count
        self._offset = offset
        self._data = data

    @property
    def total(self):
        """
        Gets the total of this DevicesEnvelope.

        :return: The total of this DevicesEnvelope.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this DevicesEnvelope.

        :param total: The total of this DevicesEnvelope.
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")

        self._total = total

    @property
    def count(self):
        """
        Gets the count of this DevicesEnvelope.

        :return: The count of this DevicesEnvelope.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this DevicesEnvelope.

        :param count: The count of this DevicesEnvelope.
        :type: int
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")

        self._count = count

    @property
    def offset(self):
        """
        Gets the offset of this DevicesEnvelope.

        :return: The offset of this DevicesEnvelope.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """
        Sets the offset of this DevicesEnvelope.

        :param offset: The offset of this DevicesEnvelope.
        :type: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")

        self._offset = offset

    @property
    def data(self):
        """
        Gets the data of this DevicesEnvelope.

        :return: The data of this DevicesEnvelope.
        :rtype: DeviceArray
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this DevicesEnvelope.

        :param data: The data of this DevicesEnvelope.
        :type: DeviceArray
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DevicesEnvelope):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
