# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EventFeedData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, event=None, ts=None, data=None):
        """
        EventFeedData - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'event': 'str',
            'ts': 'int',
            'data': 'dict(str, object)'
        }

        self.attribute_map = {
            'event': 'event',
            'ts': 'ts',
            'data': 'data'
        }

        self._event = event
        self._ts = ts
        self._data = data

    @property
    def event(self):
        """
        Gets the event of this EventFeedData.
        Event

        :return: The event of this EventFeedData.
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """
        Sets the event of this EventFeedData.
        Event

        :param event: The event of this EventFeedData.
        :type: str
        """

        self._event = event

    @property
    def ts(self):
        """
        Gets the ts of this EventFeedData.
        Timestamp

        :return: The ts of this EventFeedData.
        :rtype: int
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """
        Sets the ts of this EventFeedData.
        Timestamp

        :param ts: The ts of this EventFeedData.
        :type: int
        """

        self._ts = ts

    @property
    def data(self):
        """
        Gets the data of this EventFeedData.
        Message Payload

        :return: The data of this EventFeedData.
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this EventFeedData.
        Message Payload

        :param data: The data of this EventFeedData.
        :type: dict(str, object)
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EventFeedData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
