# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class NotifMessage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, uid=None, cts=None, data=None, mid=None, sdid=None, mv=None, sdtid=None, ts=None):
        """
        NotifMessage - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'uid': 'str',
            'cts': 'int',
            'data': 'dict(str, object)',
            'mid': 'str',
            'sdid': 'str',
            'mv': 'str',
            'sdtid': 'str',
            'ts': 'int'
        }

        self.attribute_map = {
            'uid': 'uid',
            'cts': 'cts',
            'data': 'data',
            'mid': 'mid',
            'sdid': 'sdid',
            'mv': 'mv',
            'sdtid': 'sdtid',
            'ts': 'ts'
        }

        self._uid = uid
        self._cts = cts
        self._data = data
        self._mid = mid
        self._sdid = sdid
        self._mv = mv
        self._sdtid = sdtid
        self._ts = ts

    @property
    def uid(self):
        """
        Gets the uid of this NotifMessage.

        :return: The uid of this NotifMessage.
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """
        Sets the uid of this NotifMessage.

        :param uid: The uid of this NotifMessage.
        :type: str
        """

        self._uid = uid

    @property
    def cts(self):
        """
        Gets the cts of this NotifMessage.

        :return: The cts of this NotifMessage.
        :rtype: int
        """
        return self._cts

    @cts.setter
    def cts(self, cts):
        """
        Sets the cts of this NotifMessage.

        :param cts: The cts of this NotifMessage.
        :type: int
        """

        self._cts = cts

    @property
    def data(self):
        """
        Gets the data of this NotifMessage.

        :return: The data of this NotifMessage.
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this NotifMessage.

        :param data: The data of this NotifMessage.
        :type: dict(str, object)
        """

        self._data = data

    @property
    def mid(self):
        """
        Gets the mid of this NotifMessage.

        :return: The mid of this NotifMessage.
        :rtype: str
        """
        return self._mid

    @mid.setter
    def mid(self, mid):
        """
        Sets the mid of this NotifMessage.

        :param mid: The mid of this NotifMessage.
        :type: str
        """

        self._mid = mid

    @property
    def sdid(self):
        """
        Gets the sdid of this NotifMessage.

        :return: The sdid of this NotifMessage.
        :rtype: str
        """
        return self._sdid

    @sdid.setter
    def sdid(self, sdid):
        """
        Sets the sdid of this NotifMessage.

        :param sdid: The sdid of this NotifMessage.
        :type: str
        """

        self._sdid = sdid

    @property
    def mv(self):
        """
        Gets the mv of this NotifMessage.

        :return: The mv of this NotifMessage.
        :rtype: str
        """
        return self._mv

    @mv.setter
    def mv(self, mv):
        """
        Sets the mv of this NotifMessage.

        :param mv: The mv of this NotifMessage.
        :type: str
        """

        self._mv = mv

    @property
    def sdtid(self):
        """
        Gets the sdtid of this NotifMessage.

        :return: The sdtid of this NotifMessage.
        :rtype: str
        """
        return self._sdtid

    @sdtid.setter
    def sdtid(self, sdtid):
        """
        Sets the sdtid of this NotifMessage.

        :param sdtid: The sdtid of this NotifMessage.
        :type: str
        """

        self._sdtid = sdtid

    @property
    def ts(self):
        """
        Gets the ts of this NotifMessage.

        :return: The ts of this NotifMessage.
        :rtype: int
        """
        return self._ts

    @ts.setter
    def ts(self, ts):
        """
        Sets the ts of this NotifMessage.

        :param ts: The ts of this NotifMessage.
        :type: int
        """

        self._ts = ts

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, NotifMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
