# coding: utf-8

"""
    ARTIK Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ValidationCallbackInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, aid=None, nonce=None):
        """
        ValidationCallbackInfo - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'aid': 'str',
            'nonce': 'str'
        }

        self.attribute_map = {
            'aid': 'aid',
            'nonce': 'nonce'
        }

        self._aid = aid
        self._nonce = nonce

    @property
    def aid(self):
        """
        Gets the aid of this ValidationCallbackInfo.
        Application id that created the subscription.

        :return: The aid of this ValidationCallbackInfo.
        :rtype: str
        """
        return self._aid

    @aid.setter
    def aid(self, aid):
        """
        Sets the aid of this ValidationCallbackInfo.
        Application id that created the subscription.

        :param aid: The aid of this ValidationCallbackInfo.
        :type: str
        """

        self._aid = aid

    @property
    def nonce(self):
        """
        Gets the nonce of this ValidationCallbackInfo.
        Nonce obtained from the validation request.

        :return: The nonce of this ValidationCallbackInfo.
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """
        Sets the nonce of this ValidationCallbackInfo.
        Nonce obtained from the validation request.

        :param nonce: The nonce of this ValidationCallbackInfo.
        :type: str
        """

        self._nonce = nonce

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ValidationCallbackInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
